"use client";

import { useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import { defaultUiConfig, type UiConfig } from "@/lib/ui-config";

type Version={id:string;status:string;config:UiConfig;created_at:string;published_at?:string};
const tones: Array<UiConfig["sounds"]["queue"]>=["alert","chime","pulse"];

export function UiConfigControls() {
 const [config,setConfig]=useState<UiConfig>(defaultUiConfig),[versions,setVersions]=useState<Version[]>([]),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const data=await apiFetch<{versions:Version[]}>("/api/admin/ui-config");setVersions(data.versions);const published=data.versions.find(v=>v.status==="PUBLISHED");if(published)setConfig(published.config);}catch(e){setError(e instanceof Error?e.message:"โหลดการตั้งค่าไม่สำเร็จ");}}
 useEffect(()=>{let active=true;apiFetch<{versions:Version[]}>("/api/admin/ui-config").then(data=>{if(!active)return;setVersions(data.versions);const published=data.versions.find(v=>v.status==="PUBLISHED");if(published)setConfig(published.config);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"โหลดการตั้งค่าไม่สำเร็จ");});return()=>{active=false;};},[]);
 function update(path:string,value:string|number|boolean){setConfig(current=>{const copy=structuredClone(current) as UiConfig;const [group,key]=path.split(".") as [keyof UiConfig,string];(copy[group] as Record<string,unknown>)[key]=value;return copy;});}
 function updateMenu(id:UiConfig["menus"][number]["id"],visible:boolean){setConfig(current=>({...current,menus:current.menus.map(menu=>menu.id===id?{...menu,visible}:menu)}));}
 async function save(){setBusy(true);setError("");setMessage("");try{const {version}=await apiFetch<{version:Version}>("/api/admin/ui-config",{method:"POST",body:JSON.stringify({config})});setMessage("บันทึกฉบับร่างแล้ว โปรดตรวจและเผยแพร่");setVersions(current=>[version,...current]);}catch(e){setError(e instanceof Error?e.message:"บันทึกไม่สำเร็จ");}finally{setBusy(false);}}
 async function publish(id:string){setBusy(true);setError("");try{await apiFetch(`/api/admin/ui-config/${id}/publish`,{method:"POST"});setMessage("เผยแพร่การตั้งค่าแล้ว — หน้าจอจะใช้ค่าใหม่เมื่อรีเฟรช");await load();}catch(e){setError(e instanceof Error?e.message:"เผยแพร่ไม่สำเร็จ");}finally{setBusy(false);}}
 return <section className="panel stack" aria-labelledby="ui-config-title"><div><h2 id="ui-config-title">ศูนย์ควบคุมหน้าจอ</h2><p className="muted">ปรับได้เฉพาะค่าที่ระบบรองรับ: สี ขนาดปุ่ม ความหนาแน่น เมนู ตำแหน่งส่วนหลัก เสียง และ SLA ไม่มีช่องให้ใส่โค้ดหรือ URL</p></div>
 {error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice success" role="status">{message}</div>}
 <div className="row"><div className="field"><label htmlFor="accent">สีหลัก</label><input id="accent" className="input" type="color" value={config.theme.accent} onChange={e=>update("theme.accent",e.target.value)}/></div><div className="field"><label htmlFor="density">ความหนาแน่น</label><select id="density" className="select" value={config.theme.density} onChange={e=>update("theme.density",e.target.value)}><option value="comfortable">ปกติ</option><option value="compact">กระชับ</option></select></div><div className="field"><label htmlFor="button-size">ขนาดปุ่ม</label><select id="button-size" className="select" value={config.theme.buttonSize} onChange={e=>update("theme.buttonSize",e.target.value)}><option value="normal">ปกติ</option><option value="large">ใหญ่</option></select></div></div>
 <fieldset className="fieldset"><legend>เมนูที่แสดง</legend>{config.menus.map(menu=><label key={menu.id} className="check-row"><input type="checkbox" checked={menu.visible} disabled={menu.id==="admin"} onChange={e=>updateMenu(menu.id,e.target.checked)}/>{menu.label}{menu.id==="admin"&&" (คงไว้เพื่อเข้าศูนย์ควบคุม)"}</label>)}</fieldset>
 <div className="row"><div className="field"><label htmlFor="counter-detail">รายละเอียดหน้าร้าน</label><select id="counter-detail" className="select" value={config.layouts.counter.detail} onChange={e=>setConfig(c=>({...c,layouts:{...c.layouts,counter:{...c.layouts.counter,detail:e.target.value as "right"|"bottom"}}}))}><option value="right">ด้านขวา</option><option value="bottom">ด้านล่าง</option></select></div><div className="field"><label htmlFor="packing-detail">รายละเอียดห้องแพ็ค</label><select id="packing-detail" className="select" value={config.layouts.packing.detail} onChange={e=>setConfig(c=>({...c,layouts:{...c.layouts,packing:{...c.layouts.packing,detail:e.target.value as "right"|"bottom"}}}))}><option value="right">ด้านขวา</option><option value="bottom">ด้านล่าง</option></select></div><div className="field"><label htmlFor="queue-sound">เสียงงานเข้า</label><select id="queue-sound" className="select" value={config.sounds.queue} onChange={e=>setConfig(c=>({...c,sounds:{...c.sounds,queue:e.target.value as typeof tones[number]}}))}>{tones.map(t=><option key={t} value={t}>{t}</option>)}</select></div></div>
 <div className="row"><div className="field"><label htmlFor="sla-grams">SLA ต่อปริมาณ (กรัม)</label><input id="sla-grams" className="input" type="number" min="1" max="5000" value={config.operations.slaGrams} onChange={e=>setConfig(c=>({...c,operations:{...c.operations,slaGrams:Number(e.target.value)}}))}/></div><div className="field"><label htmlFor="sla-seconds">SLA (วินาที)</label><input id="sla-seconds" className="input" type="number" min="1" max="3600" value={config.operations.slaSeconds} onChange={e=>setConfig(c=>({...c,operations:{...c.operations,slaSeconds:Number(e.target.value)}}))}/></div><div className="field"><label htmlFor="overdue-seconds">เตือนคิวค้าง (วินาที)</label><input id="overdue-seconds" className="input" type="number" min="30" max="3600" value={config.operations.overdueSeconds} onChange={e=>setConfig(c=>({...c,operations:{...c.operations,overdueSeconds:Number(e.target.value)}}))}/></div></div>
 <div className="row"><button className="button" type="button" disabled={busy} onClick={()=>void save()}>บันทึกฉบับร่าง</button></div>
 <div className="data-table-wrap"><table className="data-table"><thead><tr><th>สถานะ</th><th>สร้างเมื่อ</th><th>จัดการ</th></tr></thead><tbody>{versions.map(v=><tr key={v.id}><td>{v.status}</td><td>{new Date(v.created_at).toLocaleString("th-TH")}</td><td>{v.status==="DRAFT"&&<button className="button secondary" disabled={busy} onClick={()=>void publish(v.id)}>เผยแพร่</button>}</td></tr>)}</tbody></table></div>
 </section>;
}
